version: 0.6.1-dev4-{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  except:
  - pi-lighting
skip_branch_with_pr: true
configuration: Release
platform: x64
image: Visual Studio 2017

init:
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
        Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_TAG_NAME.TrimStart("v"))"
      }

before_build:
- ps: >-
    (Get-Content Project-Aurora\Project-Aurora\Properties\AssemblyInfo.cs) -replace '\[assembly: AssemblyFileVersion\("(.*)"\)\]', "[assembly: AssemblyFileVersion(`"$($env:APPVEYOR_BUILD_VERSION)`")]" | Set-Content Project-Aurora\Project-Aurora\Properties\AssemblyInfo.cs
- cmd: >-
    git submodule update --init --recursive
    
    cd Project-Aurora
    
    nuget restore

build:
  project: Project-Aurora\Project-Aurora.sln
  verbosity: minimal

artifacts:
  - path: Build\Release
    name: Aurora-v$(appveyor_build_version)
    type: zip
    
deploy:
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: BawzLen0V83DjFE11VqpdO3eDPMDDsrWTaQsswrLcKcn2DF/hviRKkdTbGOX6kSL
  artifact: Build\Aurora-v$(appveyor_build_version).zip          
  draft: true
  prerelease: false
  on:
    appveyor_repo_tag: true